// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvDnbhXbDqWvezA1AQXPae6kJkow1KJAY',
    appId: '1:244908008705:web:a9676a8aa35c02bad16700',
    messagingSenderId: '244908008705',
    projectId: 'money-management-6dd9b',
    authDomain: 'money-management-6dd9b.firebaseapp.com',
    storageBucket: 'money-management-6dd9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABI73Pi_vRPn1g4gExQQjQsDK8Bto5ZMs',
    appId: '1:244908008705:android:30657002cde08551d16700',
    messagingSenderId: '244908008705',
    projectId: 'money-management-6dd9b',
    storageBucket: 'money-management-6dd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQGu0u_KteFZuw4SwNrwtBqGIeZ9GzII',
    appId: '1:244908008705:ios:1655e5bd73ef61ded16700',
    messagingSenderId: '244908008705',
    projectId: 'money-management-6dd9b',
    storageBucket: 'money-management-6dd9b.appspot.com',
    iosClientId: '244908008705-44fn7jpju8r5374dckooe8tar1rr14ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQGu0u_KteFZuw4SwNrwtBqGIeZ9GzII',
    appId: '1:244908008705:ios:1655e5bd73ef61ded16700',
    messagingSenderId: '244908008705',
    projectId: 'money-management-6dd9b',
    storageBucket: 'money-management-6dd9b.appspot.com',
    iosClientId: '244908008705-44fn7jpju8r5374dckooe8tar1rr14ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyManagement',
  );
}
